[build]
command = "npm run build"
publish = ".next"

[[redirects]]
  from = "/*/////"
  to = "/"
  status = 301

[[redirects]]
  from = "/repair/(//)+"
  to = "/repair/"
  status = 301

[[redirects]]
  from = "/delivery/(//)+"
  to = "/delivery/"
  status = 301

[[redirects]]
  from = "/about/(//)+"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/contacts/(//)+"
  to = "/contacts/"
  status = 301

[[redirects]]
  from = "/repair/household/:brand/(//)+"
  to = "/repair/household/:brand/"
  status = 301

[[redirects]]
  from = "/repair/built-in/:brand/(//)+"
  to = "/repair/built-in/:brand/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  force = true
  status = 301

[[redirects]]
  from = "/repair/household/:brand/index.html"
  to = "/repair/household/:brand/"
  status = 301

[[redirects]]
  from = "/repair/built-in/:brand/index.html"
  to = "/repair/built-in/:brand/"
  status = 301

[[redirects]]
  from = "/delivery/index.html"
  to = "/delivery/"
  status = 301

[[redirects]]
  from = "/about/index.html"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/contacts/index.html"
  to = "/contacts/"
  status = 301

[[redirects]]
  from = "/repair/index.html"
  to = "/repair/"
  status = 301

[[plugins]]
  package = "@netlify/plugin-nextjs"